baseURL = "https://xusiwei.github.io/"
languageCode = "zh-CN"
theme = "maupassant"
title = "思维的博客"
toc = true
disablePathToLower = true
googleAnalytics = "UA-75067552-1"
hasCJKLanguage = true

[author]
name = "Siwei Xu"

[params]
  author = "Siwei Xu"
  subtitle = "专注C++、Linux、Android"
  keywords = "android,c++,go,golang,java,python,软件架构,机器学习"
  description = "专注于软件开发、算法设计，包括但不限于服务端、移动端等平台"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "2006-01-02, 15:04"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1
  [[menu.main]]
    identifier = "links"
    name = "链接"
    url = "/links/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[indexes]
  tag = "tags"
  category = "categories"

[params.cc]
  name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
  link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  weibo = "xu4v"
  github = "xusiwei"


