baseURL = "https://xusiwei.github.io/"
title = "Siwei's site."

languageCode = "zh-CN"
theme = "maupassant"
disablePathToLower = true
hasCJKLanguage = true
enableEmoji = true
googleAnalytics = "UA-75067552-1"
toc = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    tabWidth = 4
    codeFences = true
    guessSyntax = false
    noClasses = true
    style = "emacs"

[author]
name = "Siwei Xu"

[params]
  author = "Siwei Xu"
  subtitle = "C++/Python/Golang on Android/Web/IoT..."
  keywords = "android,c++,go,golang,java,python,软件架构,机器学习"
  description = "软件开发、算法设计，包括但不限于服务端、移动端等平台"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "2006-01-02, 15:04"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1
  [[menu.main]]
    identifier = "links"
    name = "链接"
    url = "/links/"
    weight = 2
  [[menu.main]]
    identifier = "notes"
    name = "笔记"
    url = "/tags/notes/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[indexes]
  tag = "tags"
  category = "categories"

[params.cc]
  name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
  link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  weibo = "xu4v"
  github = "xusiwei"

